### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AhmadVakili** [pkopper/deeppamm#68]
Hello,
I got this error.

```{r}
> DEEPPAMM$make_model()
Error in P[[i]][[subnetname]] : 
  attempt to select less than one element in get1index
```

**Comment by AhmadVakili** [comment]
Hello, @pkopper 
Do you have any idea how for solve it or can you help me to pass this?

**Comment by pkopper** [comment]
Hi, does the error persist? Can you provide a reproducible example?

**Comment by AhmadVakili** [comment]
Hello, thank you for your response. I actually executed the code and example you provided.And I received this error

**Comment by pkopper** [comment]
interesting, this behaviour is not occuring on my machine and server. Can you provide details on your session?
Then, I try to reproduce the error. For completeness can I also ask you to paste the code into here so the reproducible error is located in this issue?

**Comment by pkopper** [comment]
still relevant @AhmadVakili ?

**Comment by pkopper** [comment]
closed due to inactivity
